- hosts: kiwi2.gentoo-ev.org

  tasks:

  - name: Add yum repository "epel" (for python-pip)
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      enabled: yes
      gpgcheck: yes
      gpgkey: https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7

  - name: Add yum repository "docker-ce-stable"
    yum_repository:
      name: docker-ce-stable
      description: Docker CE Stable - $basearch
      baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
      enabled: yes
      gpgcheck: yes
      gpgkey: https://download.docker.com/linux/centos/gpg

  - name: Install distro packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
    # Debugging tools
      - htop
      - tmux
      - wget
    # Build and runtime dependencies
      - docker-ce
      - git
      - python-pip
    # VM maintenance
      - yum-cron

  - name: Install docker-compose
    pip:
      name: docker-compose

  - name: Add Docker users
    user:
      name: "{{ item }}"
      groups: docker
      append: yes
    with_items:
      - distrowatch-gentoo-ev-org
      - gentoo-de
      - gentoo-ev-org
      - images-gentoo-ev-org
      - ssl-reverse-proxy

  - name: Clone/sync Git repositories
    git:
      repo: "{{ item.repo }}"
      remote: github-readonly
      dest: "/home/{{ item.user }}/git-clone"
      update: yes
    become_user: "{{ item.user }}"
    with_items:
      - {user: 'distrowatch-gentoo-ev-org', repo: 'https://github.com/gentoo-ev/distrowatch.gentoo-ev.org.git'}
      - {user: 'gentoo-de', repo: 'https://github.com/gentoo-ev/www.gentoo.de.git'}
      - {user: 'gentoo-ev-org', repo: 'https://github.com/gentoo-ev/www.gentoo-ev.org.git'}
      - {user: 'images-gentoo-ev-org', repo: 'https://github.com/gentoo-ev/images.gentoo-ev.org.git'}
      - {user: 'ssl-reverse-proxy', repo: 'https://github.com/hartwork/docker-ssl-reverse-proxy.git'}

  - name: Apply reverse proxy sites.cfg
    copy:
      src: files/kiwi2/ssl-reverse-proxy-sites.cfg
      dest: /home/ssl-reverse-proxy/git-clone/sites.cfg
      owner: ssl-reverse-proxy
      group: ssl-reverse-proxy

  - name: Generate reverse proxy Caddyfile
    command: ./Caddyfile.generate
    args:
      chdir: /home/ssl-reverse-proxy/git-clone/
      # DISABLED: creates: /home/ssl-reverse-proxy/git-clone/Caddyfile
    become_user: ssl-reverse-proxy

  - name: Start services + enable auto-start
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - docker
      - yum-cron

  - name: Configure yum-cron to auto-apply updates
    ini_file:
      path: /etc/yum/yum-cron.conf
      section: commands
      option: apply_updates
      value: 'yes'
      mode: 0600
    register: yum_cron_conf

  - name: Restart service yum-cron
    service:
      name: yum-cron
      state: restarted
    when: yum_cron_conf.changed

  - name: Create internal Docker network "ssl-reverse-proxy"
    shell: docker network inspect ssl-reverse-proxy || docker network create --internal ssl-reverse-proxy
    register: docker_network
    changed_when: "docker_network.stdout == '[]\n'"

  - name: Launch Docker containers (may take a while!)
    docker_service:
      project_src: "/home/{{ item }}/git-clone"
      state: present
    become_user: "{{ item }}"
    with_items:
      - distrowatch-gentoo-ev-org
      - gentoo-de
      - gentoo-ev-org
      - images-gentoo-ev-org
      - ssl-reverse-proxy
